<?php

namespace My\BotBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

/**
 * AuctionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuctionRepository extends EntityRepository
{
	/**
	 * Get hydrated array
	 */
	public function getHydrated($status)
	{
		$qb = $this->getEntityManager()->createQueryBuilder();
		if ($status == 'active') {
			$qb->select('a')->from('\MyBotBundle:Auction', 'a')
				->where('a.status = 1')
				->andWhere('a.endAt > ?2')->setParameter(2, date('Y-m-d H:i:s', strtotime('-10 minutes')))
				->orderBy('a.endAt', 'ASC')
				->setMaxResults(3);
		} else {
			$qb->select('a')->from('\MyBotBundle:Auction', 'a')
				->where('a.status = 0')
				->orderBy('a.endAt', 'DESC')
				->setMaxResults(1);
		}

		$info = $qb->getQuery()->getResult();
		$data = $this->hydrate($info);
		return $data;
	}


	/**
	 * Hydrates auction for ko
	 */
	private function hydrate($info)
	{
		$data = array();
		foreach ($info as $item) {
			$data[] = array(
				'auctionId'	=> $item->getId(),
				'status'	=> $item->getStatus(),
				'step'		=> $item->getStep(),
				'startAt'	=> $item->getStartAt()->format('Y-m-d H:i:s'),
				'endAt'		=> $item->getEndAt()->diff(new \DateTime())->format('%R%H:%I:%S'),

				'productId'		=> $item->getProduct()->getId(),
				'productName'	=> $item->getProduct()->getName(),
				'productRetail'	=> $item->getProduct()->getRetail(),

				'price'		=> ($item->getBids()->count() ? $item->getBids()->last()->getPrice() : '-.--'),
				'userId'	=> ($item->getBids()->count() ? $item->getBids()->last()->getUser()->getId() : '-'),
				'userName'	=> ($item->getBids()->count() ? $item->getBids()->last()->getUser()->getUsername() : '-'),
				'source'	=> ($item->getBids()->count() ? $item->getBids()->last()->getSource() : '-'),
			);
		}

		usort($data, function($a, $b) {return ($a['auctionId'] >= $b['auctionId'] ? 1 : -1);});

		return $data;
	}


	/**
	 * Get Auctions to scrape
	 */
	public function getScrapeIds()
	{
		$qb = $this->getEntityManager()->createQueryBuilder();
		$auctions = $qb->select('a')->from('\MyBotBundle:Auction', 'a')
			->where('a.status = 1')
			->getQuery()
			->getResult();

		if (!$auctions) {
			return $this->getNextScrapeIds();
		}

		$data = array();

		foreach ($auctions as $auction) {

			// skip open auctions but that has expired (only if up to date)
			if (!is_null($auction->getUpdatedAt()) && $auction->getUpdatedAt() > new \DateTime('-1 minute')) {
				if ($auction->getEndAt() < new \DateTime('-10 minutes')) {
					continue;
				}
			}

			$data['auction_' . $auction->getId()] = $auction->getId();
		}

		if (count($data) < 4) {
			$nextScrapeIds = $this->getNextScrapeIds();
			$data = array_merge($data, $nextScrapeIds);
		}

		return $data;
	}


	/**
	 * Get Next Scrape IDs
	 * @see getScrapeIds
	 */
	private function getNextScrapeIds()
	{
		$qb = $this->getEntityManager()->createQueryBuilder();
		$lastId = $qb->select('a.id')->from('\MyBotBundle:Auction', 'a')
			->orderBy('a.id', 'DESC')
			->setMaxResults(1)
			->getQuery()
			->getResult();

		if (!$lastId) {
			$lastId[0]['id'] = 7280;
		}

		$data = array();
		while (count($data) < 16) {
			$data['auction_' . $lastId[0]['id']] = (string)$lastId[0]['id'];
			$lastId[0]['id']++;
		}

		return $data;
	}
}