<?php

namespace My\BotBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BidderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BidderRepository extends EntityRepository
{
}